site_name: Gale Documentation
site_url: https://pherngpy.github.io/


# theme 
theme:
  name: readthedocs
  
  

  # 404 page
  

  # Necessary for search to work properly
  

  # Default values, taken from mkdocs_theme.yml
  

